### ISSUE TITLE
Need chef_update resource to use this

### ISSUE THREAD

**Issue by lamont-granquist** [chef/mixlib-install#1]
Leaving this here since I think it'll be easier to find rather than in the chef/chef repo.

I want to be able to do this:

```ruby
chef_update "12.4.1"
```

And just have chef update itself with some sane default behavior like the omnibus_updater cookbook.

Behind that I want two different providers (with 1:1 resources) that do omnitruck and packagecloud based installs.

```ruby
omnitruck_chef_update "12.4.1"
packagecloud_chef_update "12.4.1"
```

The packagecloud provider would wire itself up on rhel/redhat/debian/ubuntu distros as the default behavior of `chef_update` whilst all other operating systems would get the omintruck method wired up to `chef_update` by default.

We need to support kill-the-chef-run-on-upgrade behavior out of the gate.  We also need to support "upgrade to the latest minor rev of whatever major rev you are" behavior out of the gate (this may be harder for packagecloud without adding some additional support to the core yum and apt package resources).

**Comment by lamont-granquist** [comment]
The packagecloud provider needs to basically do this:

```ruby
packagecloud_repo "chef/stable" do
  type "deb" # or "rpm"
end

package "chef" do
  version node['myorg']['chef-client-version']
  action :install
  notifies :run, 'ruby_block[omnibus chef killer]', :immediately
end

# Continuing with a chef client run after the client has been upgraded will give undetermined results
ruby_block 'omnibus chef killer' do
  block do
    raise 'New omnibus chef version installed. Killing Chef run!'
  end
  action :nothing
end
```

**Comment by lamont-granquist** [comment]
(of course packagecloud_repo isn't in core, which is another fussy detail)

**Comment by lamont-granquist** [comment]
We could also support syntax like:

```ruby
chef_update :latest  # actually the lastest minor release in the major 
chef_update :major_version_upgrade  # really latest, allowing major releases to upgrade
chef_update :nightlies # wooooo!
```

**Comment by sersut** [comment]
I completely agree with this and we can cover some of this work under `Auto Update Chef Client in CI` effort. [This](https://github.com/chef-cookbooks/chef-ingredient/pull/33) is the first step in that direction. Next step will be utilizing `mixlib-install` to do the same via `install.sh` and third step will be adding specific logic around using `:latest` `nightlies` etc.. as version.

**Comment by lamont-granquist** [comment]
As soon as I clear my WIP limit out a bit I'm going to do this, should be able to knock it out.  Should be able to deliver it in a couple of weeks.

**Comment by echohack** [comment]
@lamont-granquist @sersut Sign me up to be your first customer / tester of this work. I am REALLY excited about having an official Chef solution to upgrading the client.

**Comment by lamont-granquist** [comment]
see https://github.com/chef-cookbooks/chef_ingredient

**Comment by sersut** [comment]
@lamont-granquist closing this since there is nothing we can do in mixlib-install to make this happen :smile:
