### ISSUE TITLE
Specify machine architecture

### ISSUE THREAD

**Issue by ajeba99** [chef/mixlib-install#101]
I would like to be able to specify the machine architecture.  This would be useful when I am installing a chef-client.  There are times where I would like to install the x86 client instead of the x64 client. This is used in the latest version of Chef Provisioning it uses the ScriptGenerator from Mixlib Install 
https://github.com/chef/chef-provisioning/blob/master/lib/chef/provisioning/convergence_strategy/install_sh.rb#L44

We can already specify the version to install in Chef Provisioning.  Specifying 32bit or 64bit would be greeeeaaat.  You think you can some in on Saturday?  ;p

**Comment by sersut** [comment]
You can do this for windows @ajeba99 after this PR: 

https://github.com/chef/mixlib-install/pull/71

Do you need it for windows or other platforms? Not sure if doing it for other platforms is going to work well though.

**Comment by tyler-ball** [comment]
@ajeba99 Try adding `install_sh_arguments: "-architecture i386"` to your convergence options. You'll need to make sure you have mixlib-install 1.0.7 installed on your provisioning machine

**Comment by ajeba99** [comment]
when I do a chef gem list | grep mixlibI see ...
````
mixlib-authentication (1.4.0)
mixlib-cli (1.5.0)
mixlib-config (2.2.1)
mixlib-install (0.7.1)
mixlib-log (1.6.0)
mixlib-shellout (2.2.6)
````
Is 1.0.7 not in the latest version of chefdk?  If not, when will it be?

**Comment by sersut** [comment]
Maybe @btm can provide an answer to that one @ajeba99.

**Comment by schisamo** [comment]
The latest ChefDK (0.13.21) ships with mixlib-install 1.0.6 which contains https://github.com/chef/mixlib-install/pull/71:

```
➜  chef --version
Chef Development Kit Version: 0.13.21
chef-client version: 12.9.41
berks version: 4.3.2
kitchen version: 1.7.3
➜  chef gem list | grep mixlib-install
mixlib-install (1.0.6)
```

I believe we can close this issue now, would you agree @sersut @tyler-ball @mwrock ?

**Comment by sersut** [comment]
Agreed. Let us know if this is still an issue @ajeba99.
