### ISSUE TITLE
grep commands use unneeded redirections

### ISSUE THREAD

**Issue by miketheman** [chef/mixlib-install#105]
There are 4 occurrences in the rendered install.sh  that use a pattern for grep to redirect stdout and stderr to /dev/null, which is not needed when using the `-q` (or `--quiet / --silent`) flags for grep.

I'm happy to replace these if there is a desire to do so.

**Comment by sersut** [comment]
I'm 👍 doing that if that will not be an issue in our less frequently used platforms. @scotthain might be able to tell if `-q` option will make them unhappy or not 😄

**Comment by scotthain** [comment]
Unfortunately on Solaris 10 and AIX you are not guaranteed to have GNU grep (and likely won't). Original oldschool grep doesn't support -q and will blow up in that case :(

Thanks for the offer!

**Comment by miketheman** [comment]
Thanks guys! Maybe when we're able to move on from those, we can revisit this.
