### ISSUE TITLE
Add Cumulus Linux

### ISSUE THREAD

**Issue by jeunito** [chef/mixlib-install#109]
Getting this error when installing chef via url on [Cumulus Linux](https://cumulusnetworks.com/): 

> Omnitruck artifact does not exist for version  on platform "cumulus linux"

[Cumulus Linux](https://cumulusnetworks.com/) is just really Debian. Can we add an alias to the latter?

**Comment by tas50** [comment]
It appears that we fixed this in 2.1.4

https://github.com/chef/mixlib-install/blob/e1f764249d1dbfec50e5bc656972d4dcb58b731e/CHANGELOG.md#214
