### ISSUE TITLE
Need support for /etc/os-release 

### ISSUE THREAD

**Issue by rhass** [chef/mixlib-install#12]
@glennmatthews originally reported this issue in [omnitruck issue #102](https://github.com/chef/omnitruck/issues/102)

install.sh does not currently know how to recognize platforms with /etc/os-release as their only platform identifier.

This seems like a valid request. 

@glennmatthews, can you add details about how to reproduce the issue? For example, what OS and version is known to have the originally reported problem?

**Comment by patrick-wright** [comment]
@glennmatthews, Are you able to provide an update for what platforms are not currently supported?

**Comment by sersut** [comment]
@rhass @glennmatthews what are the platforms that we do not cover right now and will be covered by it? 

I am a bit hesitant because just getting output of `/etc/os-release` as a platform will not work with the matching platform mapping or publishing logic in omnitruck and our CI infra.

**Comment by glennmatthews** [comment]
I *think* this has already been addressed by #26.
