### ISSUE TITLE
Add chef automate support

### ISSUE THREAD

**Issue by poliva83** [chef/mixlib-install#123]
I don't see chef automate in ProductMatrix (https://github.com/chef/mixlib-install/blob/master/lib/mixlib/install/product.rb#L170) so I assume its currently not supported.

Was hoping to use https://github.com/chef-cookbooks/chef-ingredient eventually to install chef automate (https://downloads.chef.io/automate/).

**Comment by wrightp** [comment]
@poliva83 It would be really helpful if you would whip up a PR

**Comment by schisamo** [comment]
@poliva83 Since the actual Automate artifact/package is just Delivery you can install it right now with a product key of `delivery`. That being said we'll catch up with @mgleasonchef, the Product Manager for Automate, and ensure Automate is properly represented in the ProductMatrix though.

**Comment by poliva83** [comment]
@schisamo So is `Automate` really just `delivery` renamed? I sort of got the impression (perhaps wrongly) that Automate is suppose to be `manage`, `analytics`, `reporting` and `delivery` combined. 

@wrightp I'd be happy to help with a PR but I first need to finish evaluating the `Automate` product (manual install). I wouldn't say this issue is super urgent yet but thought i'd log issue since I noticed it didn't seem to be represented yet in product matrix.

**Comment by schisamo** [comment]
@poliva83 At this moment Automate is actually two components: Visibility and Workflow which are delivered in the existing Delivery package. Manage, Analytics, Reporting are separate products that live outside of Automate.
