### ISSUE TITLE
Allow force of HTTP for downloading files so we can cache response

### ISSUE THREAD

**Issue by amontalban** [chef/mixlib-install#138]
Moving chef/chef#5271 to here.

It would be great if we can have a flag to force HTTP for downloading so we can cache the response in proxy (Polipo in this case).

I'm using FreeBSD and Ubuntu guests.

Thanks!

**Comment by wrightp** [comment]
Try setting environment variable `PACKAGE_ROUTER_ENDPOINT` to  `http://packages.chef.io`. No guarantees :)
