### ISSUE TITLE
Support for Windows 10?

### ISSUE THREAD

**Issue by webframp** [chef/mixlib-install#169]
Went to install chefdk 1.0 using `mixlib-install`, per blog post: https://blog.chef.io/2016/11/17/announcing-release-chefdk-1-0/, but it doesn't seem to be working as expected. I'm using Powershell.

Just dropping this here in case there's some helpful info.
```
C:\> chef -v
Chef Development Kit Version: 0.19.6
chef-client version: 12.15.19
delivery version: master (802e801d920ea6b6d48db735aa7c6e7a6194bea4)
berks version: 5.1.0
kitchen version: 1.13.2

C:\> mixlib-install download chefdk -v 1.0.3
Querying for artifact with options:
{
  "channel": "stable",
  "product_name": "chefdk",
  "product_version": "1.0.3",
  "platform": "windows",
  "platform_version": "2016",
  "architecture": "x86_64"
}
No results found.
```

Yet it is up on https://downloads.chef.io/chef-dk/windows/ at: https://packages.chef.io/stable/windows/2008r2/chefdk-1.0.3-1-x86.msi
 
Versions of other stuff:
```
C:\>  (Get-WmiObject Win32_OperatingSystem).Name
Microsoft Windows 10 Enterprise|C:\WINDOWS|\Device\Harddisk0\Partition2

C:\> uname -a
MSYS_NT-10.0 US90A271W 2.5.0(0.295/5/3) 2016-03-31 18:47 x86_64 Msys

C:\> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by wrightp** [comment]
Thank you for reporting this. Platform detection is returning platform version as `2016` which is not a version we create a specific build for. I am thinking that the cli utility needs to set the backwards compat platform version option and it should work. Marking this as a bug.

**Comment by schisamo** [comment]
@webframp The following will also work:

```
mixlib-install download chefdk -v 1.0.3 --platform windows --platform-version 2008r2
```

**Comment by webframp** [comment]
Just confirming @schisamo that does indeed work, thanks for the tip!
