### ISSUE TITLE
Chef re-installing when not required

### ISSUE THREAD

**Issue by NickLaMuro** [chef/mixlib-install#17]
Most of this issue spawns from an issue I opened up in `test-kitchen`, and to avoid repeating all the information that I posted there, I will just direct you to that issue:

https://github.com/test-kitchen/test-kitchen/issues/846

After looking at the master branch, I found out that `test-kitchen` is in the process (it seems) to making use of this repository to install chef instead of supporting it itself, which makes sense.

The Problem
------------------
If you look at my comments to my original issue, this was originally changed because the `chef-solo` bin was lying about it's version number in certain releases, and in my case, the `version-manifest.txt` provided by omnibus was also lying about it's version number as well.

My solution, and [the one prior to it](https://github.com/test-kitchen/test-kitchen/pull/788), are clearly working around inaccurate information provided by the `chef-solo` and `omnibus` and really should be fixed in those places.  But that said, my guess is since they are older versions that they will end up getting tossed in the "won't fix" pile and not considered.

I am hoping that we can address this in some way, whether it is within this repo or elsewhere, but I thought I would at least get some eyes on it where active development seems to be happening.

Thanks!

**Comment by patrick-wright** [comment]
@NickLaMuro Are you still having this issue?

**Comment by NickLaMuro** [comment]
Hey @patrick-wright 

It unfortunately has been a while since I have gotten a chance to look over this and see, but I have some side project chef stuff that I am working on this weekend so I hopefully will see if I run into it then.  I will take a look at my write up in https://github.com/test-kitchen/test-kitchen/issues/846 for reference and let you know what I find this weekend.

If I flake out and fail to follow up in a timely manner (not the first time that as happened, I am sure), feel free to close this issue.

Thanks!

**Comment by patrick-wright** [comment]
Let's reopen this issue if needed.

**Comment by NickLaMuro** [comment]
Will do, sorry for the delay... :disappointed:
