### ISSUE TITLE
Return `*.appx` Windows packages for Windows Nano

### ISSUE THREAD

**Issue by mwrock** [chef/mixlib-install#189]
I noticed that we are now generating chef-client appx packages in artifactory unstable. The chef client pipeline looks to be broken since 2/23 but I'm curious if the pieces are in place once the pipeline clears to drop those packages in current and eventually stable. Looking at the code here, it looks like https://omnitruck.chef.io/current/chef/metadata?v=13&p=windows&pv=2016nano&m=x86_64 would be the URL that would fetch them.

**Comment by schisamo** [comment]
@mwrock What does Ohai return for this particular platform version? Also would it be better to use a marketing name of `nano` as opposed to `2016nano` or do we expect a `2017nano` at some point?

**Comment by mwrock** [comment]
@schisamo nano is tied to windows server 2016. In fact you need t oextract the nano image from a 2016 server install. So conceivably there will be future nanos. Of course its hard to say if they will in fact continue to be called nano.

The ohai data looks identical to a server 2016 installation. There is a registry setting that we check in https://github.com/chef/mixlib-install/blob/64f2b17cb9ef1a4fe214c470bf34bfb0fef07502/lib/mixlib/install/generator/powershell/scripts/helpers.ps1.erb#L3-L18 to detect nano.

**Comment by wrightp** [comment]
released as part of 3.1
