### ISSUE TITLE
Support download URL overrides for install scripts

### ISSUE THREAD

**Issue by wrightp** [chef/mixlib-install#193]
install.sh and install.ps1 each resolve the download URLs via queried metadata. test-kitchen supports a provisioner setting called `install_msi_url` which allows install.ps1 scripts to download and install a package from a specified URL.

For feature parity this will be required. This would also be a useful feature which would bypass much of the install scripts' functionality. This would be easy enough to add to both installer scripts.

**Comment by wrightp** [comment]
This was partially implemented in #202 . Still need to add a script param and update the powershell script.

**Comment by wrightp** [comment]
Also need ensure that metadata is not queried. That step is not necessary.

**Comment by jvogt** [comment]
The equivalent updates for powershell are in https://github.com/chef/mixlib-install/pull/216

**Comment by wrightp** [comment]
done
