### ISSUE TITLE
Synchronize platform names with cookbook chef_client_updater

### ISSUE THREAD

**Issue by 4-20ma** [chef/mixlib-install#215]
I'm attempting to use the cookbook `chef_client_updater` on CentosOS 6.5. The cookbook resource compares node platform against `mixlib-install` artifacts

- cookbook `chef_client_updater` uses `node['platform']` which is `centos`
- gem `mixlib-install` returns `el`

Not sure whether `centos` or `el` is correct/preferred platform name, but the Chef updater cookbook does not currently work as-is with CentOS. I've created an issue in the cookbook repo. @lamont-granquist suggests this is better fixed here.

Refer to https://github.com/chef-cookbooks/chef_client_updater/issues/31

**Comment by wrightp** [comment]
The issue is working as expected. Mixlib install will accept the any overridden platform value. See response in. refer back to chef-cookbooks/chef_client_updater#31 comment
