### ISSUE TITLE
Windows architecture detection failure in helpers.ps1.erb

### ISSUE THREAD

**Issue by nweddle** [chef/mixlib-install#230]
In the PowerShell `helpers.ps1.erb` template, the `Get-Win32OS` function is called to collect Windows OS details via WMI and return the results as an object with properties.

However, the function goes on to set the object result into a Windows system environment variable: `$env:win32OS`. Doing so converts the object to a string, using only the `Caption` property. Any other properties are discarded and are no longer available.

This causes the `Get-PlatformVersion` and `Get-PlatformArchitecture` functions to return invalid results.

Changing lines 29 to 35 to use a PowerShell variable such as `$win32OS`, as opposed to an environment variable `$env:win32OS`, should return  the `Get-Win32OS` function back to expected behavior.

https://github.com/chef/mixlib-install/blob/7957417e1e51af7d013e12fb60453d26a95433fb/lib/mixlib/install/generator/powershell/scripts/helpers.ps1.erb#L29-L35

**Comment by wrightp** [comment]
@nweddle If you've diagnosed the problem would you mind please submitting a PR and then test your changes? Thanks
