### ISSUE TITLE
platform_detection.sh incorrectly parses /etc/system-release on Amazon Linux 2017.12 LTS Release Candidate

### ISSUE THREAD

**Issue by EdouardMYOB** [chef/mixlib-install#252]
```
elif test -f "/etc/system-release"; then
  platform=`sed 's/^\(.\+\) release.\+/\1/' /etc/system-release | tr '[A-Z]' '[a-z]'`
  platform_version=`sed 's/^.\+ release \([.0-9]\+\).*/\1/' /etc/system-release | tr '[A-Z]' '[a-z]'`
  # amazon is built off of fedora, so act like RHEL
  if test "$platform" = "amazon linux ami"; then
    # FIXME: remove client side platform_version mangling and hard coded yolo, and remapping to deprecated "el"
    platform="el"
    platform_version="6.0"
  fi
```

is looking for a match "amazon linux ami", but on Amazon Linux 2017.12 LTS Release Candidate `/etc/system-release` contains "Amazon Linux release 2.0 (2017.12) LTS Release Candidate", so the platform sed command returns "amazon linux", and the code falls through rather than matching.

This ends up with platform_detection.sh returning "amazon linux 2.0 x86_64" instead of "el 6 x86_64", and things that rely on the output thinking that the architecture is "2.0", not "x86_64"

**Comment by wrightp** [comment]
Was this fixed as part of https://github.com/chef/mixlib-install/pull/262?

**Comment by wrightp** [comment]
Reopening this ticket. This change caused a regression exposed by chef-ingredient. https://github.com/chef-cookbooks/chef-ingredient/issues/228 . Self-assigning.

**Comment by wrightp** [comment]
This code example is old.  If this issue is still occurring with the latest version we can create a new issue.
