### ISSUE TITLE
Bug: Windows Server 2019 missing from Windows Installer platform detection

### ISSUE THREAD

**Issue by danielcbright** [chef/mixlib-install#300]
### Bug Report:
Add Windows Server 2019 to the `Get-PlatformVersion` function for the Windows install powershell script
### Describe the Bug:
Any user using Windows Server 2019 has their OS detected as 2016 during installations.

### Current Alternative
Currently Windows Server 2019 installs work, they just detect as 2016.

### Can We Help You Implement This?:
It looks like the code here needs to be updated with a new Regex for the 2019 semver - https://github.com/chef/mixlib-install/blob/b7f314748dbc0520fb0ec4e6f02a8c8f8c2c66c4/lib/mixlib/install/generator/powershell/scripts/helpers.ps1.erb#L4

**Comment by tas50** [comment]
Fixed by #301
