### ISSUE TITLE
Platform detection fails for Amazon Linux 1

### ISSUE THREAD

**Issue by siddhu208** [chef/mixlib-install#393]
# Version:

[Version of the project installed]

# Environment:

amazon linux 2018.03 x86_64

# Scenario:

Installing on Amazon linux 1 gives the following error
amazon linux ami 2018.03 x86_64
Getting information for chef stable  for amazon linux ami...
downloading https://omnitruck.chef.io/stable/chef/metadata?v=&p=amazon linux ami&pv=2018.03&m=x86_64
  to file /tmp/install.sh.27900/metadata.txt
trying wget...
trying curl...
cat: /tmp/install.sh.27900/metadata.txt: No such file or directory

grep: /tmp/install.sh.27900/metadata.txt: No such file or directory
downloaded metadata file is corrupted or an uncaught error was encountered in downloading the file...
Version:

Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
More Chef support resources can be found at https://www.chef.io/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

# Steps to Reproduce:

sudo curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -v 12.22.5

# Expected Result:

Expected chef to install correctly

# Actual Result:

Fails with above error

**Comment by siddhu208** [comment]
This is a very small bug, created a PR for it at https://github.com/chef/mixlib-install/pull/394
This is a very critical issue for us as many production systems use this and fail as of now. Please merge/fix as soon as possible. Thank you.

**Comment by milansanjeev** [comment]
Yes we are observing same issue since last weeks can someone please look and merge this PR.

**Comment by siddhu208** [comment]
This is now working post merge. Iam closing this issue.
