### ISSUE TITLE
Consider renaming accessor / options

### ISSUE THREAD

**Issue by jtimberman** [chef/mixlib-install#4]
In #3, I made all the options dynamically send to `self`. I left in the condition for:

* `base` -> `base_url`
* `sudo` -> `use_sudo`
* `sudo_command`, which sets `use_sudo` to true

Perhaps we could rename the option, or the accessor? The API is still pre-1.0 so we won't upset the world of semver :cookie:. Handling sudo may be best done in a separate method.

**Comment by thommay** [comment]
I think I'd rename `base` to `base_url` across the board, or possibly something yet more descriptive. and maybe `sudo` to `use_sudo`, too.

**Comment by jtimberman** [comment]
Sure, either way, my point being consolidation of the options so we can use the dynamic dispatch from #3 for more things to reduce the complexity and cognitive reasoning of that code.

**Comment by thommay** [comment]
All done, thanks for the PR and the suggestions!
