### ISSUE TITLE
Should make it easy to support custom download URLs

### ISSUE THREAD

**Issue by thommay** [chef/mixlib-install#43]
We should ensure that users behind a firewall that mirror our packages can easily get test-kitchen and friends to download the correct thing.

essentially
```
#!/bin/sh
rpm -ivh http://example.local/path/to/chef-12-whatever.rpm
```
is often good enough in that situation.

**Comment by scarolan** [comment]
Yes, this sums up our situation.  The user story is always the same:

"I am an enterprise chef user and for various reasons cannot access the install.sh and chef installer files from my current network.  I need to be able to fetch the install script(s) and chef installer from an internally hosted location, like a file server on the local LAN."  

If we could provide some really simple install.sh scripts, we can use chef_omnibus_url to point at the custom install.sh

**Comment by patrick-wright** [comment]
This feature is available in master and will be in the next minor(major?) release.

mixlib-install can generate the install script for unix and windows, and the url server can also be configured via a context.    I _believe_ what we have now will work, but we should sync up to verify.

**Comment by sersut** [comment]
We have a few ways to make this happen now: 

1. A user can mirror our apt / yum repos and use `chef-ingredient` to install Chef products. There is a `custom_repo` property which can make that happen. 
2. A user can again use `chef-ingredient` and install any Chef product by pointing to a local file. 

Doing this in mixlib-install will be very hard and incomplete for at least some of the cases. 

Closing this now. Let us know if the `chef-ingredient` path is not an acceptance solution.
