### ISSUE TITLE
support/install_command.ps1 should be under 3040 with command variables and base64 encoded

### ISSUE THREAD

**Issue by hh** [chef/mixlib-install#6]
I have a feeling that [support/install_command.ps1](https://github.com/chef/mixlib-install/blob/master/support/install_command.ps1) longer than what we've had in the past. WinRb/WinRM#41 notes that ```3040``` seems to be the max and I'm seeing ```3058``` now. If we can drop that by at least 18 characters or so I think things will work.

Errors are showing up in chef/knife-windows#262 and chef/chef-provisioning#431 when trying to hit windows2012 nodes on ec2.

Do we have a test suite for knife-ec2 and chef-provisioning-ec2 hitting  for ec2 windows2012 nodes?

https://github.com/chef/mixlib-install/commit/a83a59e47508e3e710e13a6e963c39472b1378a8#commitcomment-13086621

**Comment by hh** [comment]
Maybe we could use Chef::Provisioning::Transport::WinRM#write_file (which chunks by default) to write the install command out to a file, then execute that via scheduled task.

**Comment by patrick-wright** [comment]
Fixed in TK
