### ISSUE TITLE
Kitchen does not upgrade installed version of chef-client on windows

### ISSUE THREAD

**Issue by vinyar** [chef/mixlib-install#68]
Seems that latest ChefDk still have the errors referenced in https://github.com/test-kitchen/test-kitchen/issues/882 and https://github.com/test-kitchen/test-kitchen/issues/847

tldr - setting the omnibus version doesn't update it.

https://github.com/chef/mixlib-install/pull/21 was supposed to address them, but I am still seeing a repro 

Environment:
```
$ chef -v                   
Chef Development Kit Version: 0.11.2
chef-client version: 12.7.2
berks version: 4.2.0
kitchen version: 1.5.0

$ vagrant plugin list  
kitchen-nodes (0.7.0)
vagrant-berkshelf (4.1.0)
vagrant-cachier (1.2.1)
vagrant-omnibus (1.4.1)
vagrant-persistent-storage (0.0.19)
vagrant-share (1.1.5, system)
vagrant-winrm (0.7.0)
```

**Comment by smurawski** [comment]
@vinyar I get the correct behavior with kitchen 1.6 and mixlib-install 0.7.1.  What version of mixlib-install do you have?

**Comment by vinyar** [comment]
just installed TK 1.6 with appbundle-updater and it seems to install the version specified.

Going to close this
