### ISSUE TITLE
Mixlib::Install.detect_platform does not work on windows

### ISSUE THREAD

**Issue by mwrock** [chef/mixlib-install#70]
This can be easily demonstrated by running the specs on a windows machine. The issue is that this method uses the "tic" method of running a shell command. It works on linux since it is likely going to invoke a bash shell but on windows this just calls into cmd.exe and thus powershell will not execute.

We should probably base64 encode the powershell and send that to the `-EncodedCommand` arg of Powershell.exe. However thats not entirely ideal since it would break on Windows Nano.

**Comment by patrick-wright** [comment]
Thanks for writing this up.  This is a known issue.  The `detect_platform` was quickly done so chef-ingredient could install chef-server using mixlib-install.  This will be fixed once all the bintray work is complete.

**Comment by mwrock** [comment]
oh ok. good enough.
