### ISSUE TITLE
Support `set -x` for debugging

### ISSUE THREAD

**Issue by curiositycasualty** [chef/mixlib-install#8]
Since this is now used by test-kitchen, had to dig through a lot of code to add `set -x` to see where `install.sh` was failing. It'd be nice if there was some way to specify that the given `cmd` be wrapped with `set -x`.

**Comment by lamont-granquist** [comment]
http://redsymbol.net/articles/unofficial-bash-strict-mode/

**Comment by lamont-granquist** [comment]
(of course bash-isms would need to be removed from that, but IFS and set -x are oooooold things)
