### ISSUE TITLE
`uname -m` on ubuntu 14.04 seems to get the machine arch wrong

### ISSUE THREAD

**Issue by lamont-granquist** [chef/mixlib-install#81]
See https://github.com/mitchellh/vagrant/issues/7185

https://omnitruck.chef.io/current/chef/metadata?v=&p=ubuntu&pv=14.04&m=i686 does not work

https://omnitruck.chef.io/current/chef/metadata?v=&p=ubuntu&pv=14.04&m=i386 works

according to the omnitruck README.md docs it looks like i386 is correct, so i don't think that recently changed with the packagecloud.io deprecation changes?

that implies that at some point we broke 32-bit installation in install.sh (probably when it got mixlib-install'd?)

also highlights the fact that we've clearly lost acceptance testing of install.sh and nobody is running it on 32-bit ubuntu...

tagging @sersut and maybe @chef/engineering-services ?

**Comment by schisamo** [comment]
@lamont-granquist This actually just happened when Omnitruck was moved over to using mixlib-install's Bintray backend:
https://github.com/chef/mixlib-install/blob/master/lib/mixlib/install/backend/bintray.rb#L192-L208

Right now this type of architecture munging is up in Omnitruck though:
https://github.com/chef/omnitruck/blob/137e7a1e082d5810dc22ed162ebbdf3278243f61/app.rb#L309-L316

Obviously that is Windows only so we might something similar for Ubuntu and EL. We basically want `i686` to map to `i386`.

**Comment by lamont-granquist** [comment]
Ah, I see the comment in the README.md was only a few days old instead of a few years old...

Yeah, that could just be:

```
    m = if params["m"].nil? || params["m"].empty? || params["m"] =~ /i[3456]86/
          "i386"
        else
          params['m']
        end
```

**Comment by schisamo** [comment]
@lamont-granquist We'll have an Omnitruck fix deployed in a few, @sersut is looking into things right now.

**Comment by lamont-granquist** [comment]
closing since this is the wrong repo...
