### ISSUE TITLE
any version of chef-client that doesnt' have version manifest wile will always assume that defined version is in use

### ISSUE THREAD

**Issue by vinyar** [chef/mixlib-install#84]
After debugging with Matt, looks like in `long_script.ps1` the following statement does not have a flag for terminating error, so it just keeps going:

  Try { $chef_version = (Get-Content $root\version-manifest.txt | select-object -first 1) }
  Catch {
    Try { $chef_version = (& $root\bin\chef-solo.bat -v) }
    Catch { $chef_version = " " }
  }

the try statement needs to have ` -ErrorAction stop`

**Comment by patrick-wright** [comment]
Fixed in PR #85
