### ISSUE TITLE
schtask support for installing chef-client on windows

### ISSUE THREAD

**Issue by hh** [chef/mixlib-install#9]
It's a dependency for getting machine_image supported for run_lists that include wsus updates and other tasks required to be run on \\LocalMachine.

Should we open a separate ticket for possibly adding 

Just getting a ticket together to track this.

From http://lists.opscode.com/sympa/arc/chef/2015-09/msg00098.html

It’s not especially hard to cause a scheduled task to run:
https://github.com/smurawski/chef-zero-scheduled-task/blob/master/lib/kitchen/provisioner/chef_zero_scheduled_task.rb is a scheduled task provisioner for t-k; i’m aiming to bring that down into mixlib-install this week so that it’s accessible to t-k’s core winrm provisioner and chef-provisioning. @thommay

**Comment by hh** [comment]
'Uploading  the PS1 script and run directly' chef/chef-provisioning#410 fixes the winrm+powershell bootstrap for windows 2012, but it still leaves 2008r2 in the cold https://github.com/chef/chef-provisioning/pull/410#issuecomment-130450745

**Comment by thommay** [comment]
that's not strictly true - as per the rest of that ticket, you can do either of the work arounds (I'd recommend building an AMI that has wmf4 on) and 2008r2 is fine.

**Comment by hh** [comment]
Is it possible to use chef_provisioning to install wmf4 without converging via schtask? I can go make a manual AMI image, but it leaves a gap in the automation.

**Comment by sersut** [comment]
Looks like we're keeping track of the scktask support in https://github.com/chef/chef-provisioning/issues/443. Closing this issue in favor of it.
