### ISSUE TITLE
Bintray backend should return http://chef.bintray.com/* URLs for some ancient platforms

### ISSUE THREAD

**Issue by schisamo** [chef/mixlib-install#91]
TL;DR some older distros have such a crufty old OpenSSL in the base install that **`https://packages.chef.io/*`**-based URLs can't be verfied:

```
$ openssl version
OpenSSL 0.9.8zh-freebsd 3 Dec 2015
$ fetch https://packages.chef.io/stable/freebsd/9/chef-12.6.0_1.amd64.sh
Certificate verification failed for /C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
43013:error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed:/usr/src/secure/lib/libssl/../../../crypto/openssl/ssl/s3_clnt.c:974:
fetch: https://packages.chef.io/stable/freebsd/9/chef-12.6.0_1.amd64.sh: Authentication error
```

 The easiest workaround is to return package urls which use a base of **`http://chef.bintray.com/*`**:

```
$ fetch http://chef.bintray.com/stable/freebsd/9/chef-12.6.0_1.amd64.sh
chef-12.6.0_1.amd64.sh                        100% of   28 MB 9828 kBps 00m03s
```

Right now the only known affected platform/versions are:

* FreeBSD 9 (**platform:** `freebsd`, **platform_version:** `9`)

Our implementation should be flexible enough to allow adding other platform/versions in the future.

This should fix https://github.com/chef/omnitruck/issues/170

/cc @sersut @patrick-wright @scotthain

**Comment by sersut** [comment]
Got it. Thanks for the investigation @schisamo. el5 is good?

**Comment by schisamo** [comment]
@sersut I have not seen the issue when bootstrapping CentOS 5 (Vagrant) or RHEL 5 (EC2).

**Comment by amyles** [comment]
I am seeing this issue (or v. similar) when bootstrapping Oracle Linux 6.5 which has OpenSSL 1.0.1e-fips 11 Feb 2013. I see this:

> Metadata URL: https://omnitruck-direct.chef.io/stable/chef/metadata?v=12&p=el&pv=6&m=x86_64
> host-50-194 Download URL: https://packages.chef.io/stable/el/6/chef-12.9.38-1.el6.x86_64.rpm
> host-50-194 \nDEBUG OUTPUT FOLLOWS:\n\nSTDERR from wget:\n\n--2016-04-19 09:47:41--  https://packages.chef.io/stable/el/6/chef-12.9.38-1.el6.x86_64.rpm
> host-50-194 Connecting to 138.3.34.194:80... connected.
> host-50-194 ERROR: certificate common name `*.bintray.com' doesn't match requested host name `packages.chef.io'.
> host-50-194 To connect to packages.chef.io insecurely, use `--no-check-certificate'.\n\nSTDERR from perl:\n\n500 handshakefailed <URL:https://packages.chef.io/stable/el/6/chef-12.9.38-1.el6.x86_64.rpm>\n\nSTDERR from python:\n\nTraceback (most recent call last):
> 

This was working previously but I guess there were possibly some changes to the CDN certs???

I'm on Chef DK 0.10.0 & chef-client version 12.5.1.

I'm also issuing the bootstrap command with the options:

> --bootstrap-wget-options '--no-check-certificate' --node-ssl-verify-mode none --bootstrap-curl-options '--insecure'
but this doesn't seem to help. Are there any workarounds? TIA

**Comment by tata2000** [comment]
The same issue with FreeBSD 10

**Comment by amyles** [comment]
Also found https://github.com/chef/omnitruck/issues/176 but the omnitruck fix mentioned doesn't seem to help on ol6 bootstrap.

**Comment by amyles** [comment]
Created a new issue at https://github.com/chef/omnitruck/issues/183 as this is closed so suspect it's not getting any attention.
